### ISSUE TITLE
Google Play相关

### ISSUE THREAD

**Issue by ghost** [YangDai2003/Number_Tic_Tac_Toe-Android#1]
打扰下大佬，刚刚在Play商店预览了下您的应用，非常喜欢，但是可惜Play商店未提供下载入口，想问下是Google的问题咩？蟹另外非常感谢大佬为我们带来这么多的Material You应用，辛苦啦w！

**Comment by YangDai2003** [comment]
> 打扰下大佬，刚刚在Play商店预览了下您的应用，非常喜欢，但是可惜Play商店未提供下载入口，想问下是Google的问题咩？蟹另外非常感谢大佬为我们带来这么多的Material You应用，辛苦啦w！

你好，感谢支持。我所有应用都在google play store的170多个地区上架的，正常来说无论你在哪个地区的play商店应该都能正常下载。可能是你的play商店有些问题? 你可以尝试退出google账号，清除缓存，再登录账号，如果还不行，尝试更新play商店至最新版本。
另外我也算不上大佬😂，也是在不断制作实用好看的应用中学习进步，一开始的几个应用可能些许简单，推荐你下载使用我的多功能计算器和OCR助手，这两个应用我做的比较完善。请积极反馈问题啊！我会尽可能快的改进修复。
再次感谢支持！！！

**Comment by ghost** [comment]
谢谢大佬回复！居然这么多天忘了回复，向您道个歉！目前访问正常了，也可以直接下载，应该是谷歌那边的问题。也再次感谢大佬的付出啦，继续加油哦www
